### ISSUE TITLE
Update to 6.14.0 on prod-preview break usage of Che SA token required for che-* namespace lockdown and introduced issue with k8s client usage

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1075]
`6.14.0` upstream version of che have updated the version of kubernetes-client form `3.1.12` to `4.1.0` break usage of Che SA token that is required for removing edit rights from *-che namespace [1]. Currently all prod-preview accounts have been switched to use OSIO token instead of Che SA token via toggle. Currently using Che SA token for communication with oso-proxy results in the following errors which prevents creation of resources in *-che namespace:

> {"@timestamp":"2018-11-15T14:07:53.744+00:00","@version":1,"message":"Workspace 'rh-che-automation-preview/wksp-muq9' with id 'workspacetmpa1qatnigx0kix' created by user 'rh-che-automation-preview'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-6","level":"INFO","level_value":20000,"identity_id":"0c08fee4-5bae-4063-ad65-091bb80a9df5"}
> {"@timestamp":"2018-11-15T14:08:01.444+00:00","@version":1,"message":"Starting workspace 'rh-che-automation-preview/wksp-muq9' with id 'workspacetmpa1qatnigx0kix' by user 'rh-che-automation-preview'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-2","level":"INFO","level_value":20000,"identity_id":"0c08fee4-5bae-4063-ad65-091bb80a9df5"}
> {"@timestamp":"2018-11-15T14:08:02.038+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspacetmpa1qatnigx0kix. Cause: Failure executing: POST at: https://osoproxy.prod-preview.openshift.io/api/v1/namespaces/rh-che-automation-preview-che/persistentvolumeclaims?identity_id=0c08fee4-5bae-4063-ad65-091bb80a9df5/ . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. forbidden: User \"system:serviceaccount:rh-che-automation-preview-che:che\" cannot post path \"/\": no RBAC policy matched. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-2","level":"WARN","level_value":30000,"identity_id":"0c08fee4-5bae-4063-ad65-091bb80a9df5"}

`Unable to perform '[rm, -rf, /tmp/job_mount/workspacewx1o628oqaekv65b]' command for the workspace 'workspacewx1o628oqaekv65b' cause: 'Failure executing: POST at: https://osoproxy.prod-preview.openshift.io/api/v1/namespaces/osio-ci-ee3-preview-che/pods?identity_id=059737ac-0c8d-45bf-9241-e750122a316e/ . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. forbidden: User \"system:serviceaccount:osio-ci-ee3-preview-che:che\" cannot post path \"/\": no RBAC policy matched. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.'","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.PVCSubPathHelper","thread_name":"PVCSubPathHelper-ThreadPool-3","level":"ERROR","level_value":40000,"identity_id":"059737ac-0c8d-45bf-9241-e750122a316e"}`

Also, currently in che-server logs there are a bunch of errors like:

```
{"@timestamp":"2018-11-15T17:47:51.349+00:00","@version":1,"message":"Could not deserialize watch event: \"/apis/build.openshift.io\",","logger_name":"io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager","thread_name":"OkHttp https://osoproxy.prod-preview.openshift.io/...","level":"ERROR","level_value":40000,"stack_trace":"com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class io.fabric8.kubernetes.api.model.WatchEvent] from String value ('/apis/build.openshift.io'); no single-String constructor/factory method
 at [Source: \"/apis/build.openshift.io\",; line: 1, column: 5]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:993)
    at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:316)
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:288)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1200)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:144)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
    at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager.readWatchEvent(WatchHTTPManager.java:302)
    at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager.onMessage(WatchHTTPManager.java:247)
    at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager$2.onResponse(WatchHTTPManager.java:176)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
"}
```

The problem with Che SA token has not been caught by PR check due to the fact, that on dev cluster OSIO token is always used for communications with oso-proxy (secrets that are passed to https://auth.(prod-preview.)openshift.io/api/token endpoint in order to obtain the token are only available on dsaas / dsaas-stg)

[1] https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844
[2] https://adminproxy.prod-preview.openshift.io/toggles/#/features/strategies/che.serviceaccount.lockdown

**Comment by ibuziuk** [comment]
PR for removing query parameter when passing identity_id to oso-proxy - https://github.com/redhat-developer/rh-che/pull/1076

**Comment by ibuziuk** [comment]
It looks like there is also a problem with processing in the `ImpersonatorInterceptor` [1]:


> {"@timestamp":"2018-11-16T10:38:43.385+00:00","@version":1,"message":"value for name Impersonate-Group == null","logger_name":"org.eclipse.che.api.core.notification.EventService","thread_name":"http-nio-8080-exec-2","level":"ERROR","level_value":40000,"stack_trace":"java.lang.NullPointerException: value for name Impersonate-Group == null\n\tat okhttp3.Headers$Builder.checkNameAndValue(Headers.java:334)\n\tat okhttp3.Headers$Builder.add(Headers.java:288)\n\tat okhttp3.Request$Builder.addHeader(Request.java:177)\n\tat io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:48)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:74)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat 

Basically, in the current version of k8s client if `Impersonate-User` header is set, at least one `Impersonate-Group` should be also set, otherwise it would result in NPE:

[1] https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java#L47

**Comment by ibuziuk** [comment]
Have opened an issue regarding `Impersonate-Group` processing -  https://github.com/fabric8io/kubernetes-client/issues/1266

**Comment by ibuziuk** [comment]
fix [1] for NPE when `Impersonate-Group` is not defined should be a part of the `4.1.1` release. Currently, we need to workaround this case on rh-che / oso-proxy side.

[1] https://github.com/fabric8io/kubernetes-client/pull/1267/files

**Comment by ibuziuk** [comment]
It looks like query parameter processing got completely broken on oso-proxy side: it is passed correctly via header:

`time="2018-11-22T17:53:48Z" level=info msg="Got header 'Impersonate-User' with value '059737ac-0c8d-45bf-9241-e750122a316e'"`

But not via query parameter where trailing `/` is added :

> time="2018-11-22T17:53:48Z" level=info msg="Got query param 'identity_id' with value '059737ac-0c8d-45bf-9241-e750122a316e/'"


`{"BackendAddr":"api.starter-us-east-2a.openshift.com","BackendName":"api1","BackendURL":{"Scheme":"https","Opaque":"","User":null,"Host":"api.starter-us-east-2a.openshift.com","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"ClientAddr":"10.129.4.1:47762","ClientHost":"54.152.38.71","ClientPort":"47762","ClientUsername":"-","DownstreamContentSize":4332,"DownstreamStatus":200,"DownstreamStatusLine":"200 OK","Duration":13805419,"FrontendName":"api1","OriginContentSize":4332,"OriginDuration":13518521,"OriginStatus":200,"OriginStatusLine":"200 OK","Overhead":286898,"RequestAddr":"osoproxy.prod-preview.openshift.io","RequestContentSize":0,"RequestCount":100518,"RequestHost":"osoproxy.prod-preview.openshift.io","RequestLine":"GET /api/v1/namespaces/osio-ci-ee3-preview-che/services?identity_id=059737ac-0c8d-45bf-9241-e750122a316e/\u0026labelSelector=che.workspace_id%3Dworkspacele6ymqdjriv7l4ne HTTP/1.1","RequestMethod":"GET","RequestPath":"/api/v1/namespaces/osio-ci-ee3-preview-che/services?identity_id=059737ac-0c8d-45bf-9241-e750122a316e/\u0026labelSelector=che.workspace_id%3Dworkspacele6ymqdjriv7l4ne","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2018-11-22T17:53:48.782324711Z","StartUTC":"2018-11-22T17:53:48.782324711Z","downstream_Cache-Control":"no-store","downstream_Content-Type":"application/json","downstream_Date":"Thu, 22 Nov 2018 17:53:48 GMT","level":"info","msg":"","origin_Cache-Control":"no-store","origin_Content-Type":"application/json","origin_Date":"Thu, 22 Nov 2018 17:53:48 GMT","request_Accept-Encoding":"gzip","request_Authorization":"REDACTED","request_Forwarded":"for=54.152.38.71;host=osoproxy.prod-preview.openshift.io;proto=https;proto-version=","request_Target":"https://api.starter-us-east-2a.openshift.com","request_User-Agent":"okhttp/3.9.1","request_X-Forwarded-For":"54.152.38.71","request_X-Forwarded-Host":"osoproxy.prod-preview.openshift.io","request_X-Forwarded-Port":"443","request_X-Forwarded-Proto":"https","time":"2018-11-22T17:53:48Z "}`

On rh-che side it is failing with the following error:

> Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. forbidden: User \"system:serviceaccount:osio-ci-ee3-preview-che:che\" cannot post path \"/\": no RBAC policy matched. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-1","level":"WARN","level_value":30000,"identity_id":"059737ac-0c8d-45bf-9241-e750122a316e"}

**Comment by ibuziuk** [comment]
che.openshift.io has been successfully updated on prod to the latest 6.14.2 upstream version.
The reason of delay was related to the fact that update to 4.1.0 version of `kubernetes-client` in upstream broke communication between rh-che and oso-proxy. The following fixes have been made in order to support the latest version of client:

- Not setting optional `Impersonate-Group` results in NPE in ImpersonatorInterceptor [1] [2]
- Passing 'identity_id' to oso-proxy only via Impersonate-User Header [3]
- Adding 'ImpersonatorInterceptor' during creation of KubernetesClient [4] 
- Applied workaround for [1] [2] on rh-che / oso-proxy [5] [6] side until `kubernetes-client` is updated to 4.1.1 version in upst [7] 

[1] https://github.com/fabric8io/kubernetes-client/issues/1266
[2] https://github.com/fabric8io/kubernetes-client/pull/1267
[3] https://github.com/redhat-developer/rh-che/pull/1089
[4] https://github.com/eclipse/che/pull/12029
[5] https://github.com/eclipse/che/pull/12029
[6] https://github.com/fabric8-services/fabric8-oso-proxy/pull/43
[7] https://github.com/eclipse/che/issues/11981
