### ISSUE TITLE
Do not log RuntimeException when user is deprovisioned

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1167]
https://errortracking.prod-preview.openshift.io/openshift_io/che6master/issues/9448/

```
InternalInfrastructureException: java.lang.RuntimeException: Could not retrieve OSO token of the user. Response from auth service: {"errors":[{"code":"unauthorized_error","detail":"user deprovisioned","status":"401","title":"Unauthorized error"}]}

    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:712)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:250)
    at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:148)
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:359)
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
...
(4 additional frame(s) were not displayed)

UncheckedExecutionException: java.lang.RuntimeException: Could not retrieve OSO token of the user. Response from auth service: {"errors":[{"code":"unauthorized_error","detail":"user deprovisioned","status":"401","title":"Unauthorized error"}]}

    at com.redhat.che.multitenant.OpenshiftUserTokenProvider.getToken(OpenshiftUserTokenProvider.java:103)
    at com.redhat.che.multitenant.RhCheInfraEnvironmentProvisioner.addTokenEnvVar(RhCheInfraEnvironmentProvisioner.java:144)
    at com.redhat.che.multitenant.RhCheInfraEnvironmentProvisioner.provision(RhCheInfraEnvironmentProvisioner.java:122)
    at com.redhat.che.multitenant.RhCheInfraEnvironmentProvisioner.provision(RhCheInfraEnvironmentProvisioner.java:55)
    at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:104)
...
(13 additional frame(s) were not displayed)

RuntimeException: Could not retrieve OSO token of the user. Response from auth service: {"errors":[{"code":"unauthorized_error","detail":"user deprovisioned","status":"401","title":"Unauthorized error"}]}

    at com.redhat.che.multitenant.OpenshiftUserTokenProvider.getOsToken(OpenshiftUserTokenProvider.java:139)
...
(18 additional frame(s) were not displayed)

java.lang.RuntimeException: Could not retrieve OSO token of the user. Response from auth service: {"errors":[{"code":"unauthorized_error","detail":"user deprovisioned","status":"401","title":"Unauthorized error"}]}

```

**Comment by ibuziuk** [comment]
@amisevsk isn't it already addressed by one of your PRs ?

**Comment by amisevsk** [comment]
@ibuziuk I'm not sure, Che seems to be putting out RuntimeExceptions unexpectedly far more than it should.

PR https://github.com/redhat-developer/rh-che/pull/1255 covers the tenant data cache, but it looks like the changes would need to be also made to `OpenShiftUserTokenProvider`. I'd need to look at it a bit more but it shouldn't be complicated.

**Comment by ibuziuk** [comment]
Closing as outdated
