### ISSUE TITLE
[Rebase oscon] Adapt new stacks.json to the new policy change

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#124]
see - https://issues.jboss.org/browse/CHE-298

**Comment by benoitf** [comment]
I'm working on that

**Comment by l0rd** [comment]
I'm reopening this issue because as I understand #160 and #158 didn't fix it completely /cc @sunix @benoitf

**Comment by sunix** [comment]
@benoitf 
`2017-07-03 13:30:56,229[ost-startStop-1]  [ERROR] [o.e.c.a.w.s.stack.StackLoader 147]   - Failed to load stack icon data for the stack with id 'java-centos'
java.io.IOException: Not found resource: stacks-images/type-java.svg
	at org.eclipse.che.commons.lang.IoUtil.getResource(IoUtil.java:134)
	at org.eclipse.che.api.workspace.server.stack.StackLoader.setIconData(StackLoader.java:142)
	at org.eclipse.che.api.workspace.server.stack.StackLoader.loadStack(StackLoader.java:109)
	at org.eclipse.che.api.workspace.server.stack.StackLoader.lambda$start$0(StackLoader.java:99)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.eclipse.che.api.workspace.server.stack.StackLoader.start(StackLoader.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at `com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)`

**Comment by benoitf** [comment]
I think it can be closed now

**Comment by benoitf** [comment]
I let @sunix confirm ;-)
