### ISSUE TITLE
Unable to start workspace due to untracked deployment

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1358]
More details in https://github.com/redhat-developer/che-functional-tests/issues/473

A few namespaces on various clusters are affected:

```
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspaceagjbf0euhcjaz8e3.dockerimage-5dcc95477f-8tp75" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=4,limits.memory=2147483648, used: limits.cpu=4,limits.memory=2147483648, limited: limits.cpu=6,limits.memory=3Gi', 'workspaceagjbf0euhcjaz8e3.dockerimage-5dcc95477f'"
```

![Screenshot from 2019-04-08 07-53-27](https://user-images.githubusercontent.com/29278800/55701530-ca637d00-59d3-11e9-878a-0215a7f96380.png)

cleaned `kkanova-che` and `osiotest2-che` manually and this should unblock testing. Some differences between 2 cases:
- `kkanova-che` had only pod and deployment whereas `osiotest2-che` had all the resources dedicated to namespaces - deployment, pod, route, svc
- `kkanova-che` 
   - Start Time: Fri, 05 Apr 2019 15:10:22 +0000
   - Restart Count:  0
- ` osiotest2-che`
   - Running for 10d
   - Restart Count:  0

Basically, we can not proceed with any other investigation until `kubernetes.labels.app:"rhche" AND kubernetes.namespace_name:"dsaas-production"` returns no results on prod cc: @pbergene

**Comment by pbergene** [comment]
@ibuziuk are these for logs coming in via tenant-log-indirector or rhche (master) itself?

**Comment by ibuziuk** [comment]
@pbergene correct rhche (master)

**Comment by Katka92** [comment]
Today, another account became broken. The account is for user ``` osiotest1a ``` on 1a cluster. Even it was only two hours old, I could not get any logs from rhche. The only log which is here is:
```
{"@timestamp":"2019-04-18T12:28:09.440+00:00","@version":1,"message":"Unable to generate signature keypair for ws workspace4cjpqr46i0h5xadk. Cause: Unable to create signature key pair because referenced workspace with id 'workspace4cjpqr46i0h5xadk' doesn't exist","logger_name":"org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager","thread_name":"http-nio-8080-exec-22","level":"ERROR","level_value":40000}
{"@timestamp":"2019-04-18T12:28:09.440+00:00","@version":1,"message":"Failed to load signature keys for ws  workspace4cjpqr46i0h5xadk. Cause: Unable to create signature key pair because referenced workspace with id 'workspace4cjpqr46i0h5xadk' doesn't exist","logger_name":"org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager","thread_name":"http-nio-8080-exec-22","level":"ERROR","level_value":40000}
```
The account ``` kkanova-preview ``` has pod ``` workspacejphawp7usecyocvm.dockerimage ``` running for 2 days now. I removed that manually today to have account for manual tests.

**Comment by amisevsk** [comment]
I found similar signature keypair logs in testing workspace starts yesterday on `2a`; I'm seeing it in roughly 1/10 starts, but in my case it doesn't result in a broken account and the message is slightly different (key-pair already exists vs. workspace does not exist). The stack trace in my case is:
```
2019-04-18 03:23:45,628[io-8080-exec-10]  [ERROR] [.m.m.a.s.s.SignatureKeyManager 141]  - Unable to generate signature keypair for ws workspacepl33rpdmp2wolmyn. Cause: Signature key pair for workspace 'workspacepl33rpdmp2wolmyn' already exists
2019-04-18 03:23:45,629[io-8080-exec-10]  [ERROR] [.m.m.a.s.s.SignatureKeyManager 105]  - Failed to load signature keys for ws  workspacepl33rpdmp2wolmyn. Cause: Signature key pair for workspace 'workspacepl33rpdmp2wolmyn' already exists
2019-04-18 03:23:45,630[io-8080-exec-10]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 398]   - Failed to generate machine token for user '3f652e0c-1874-4de5-9c62-602634cb5cc2' and workspace 'workspacepl33rpdmp2wolmyn'. Cause: 'Signature key pair for workspace 'workspacepl33rpdmp2wolmyn' already exists'
org.eclipse.che.api.workspace.server.token.MachineTokenException: Failed to generate machine token for user '3f652e0c-1874-4de5-9c62-602634cb5cc2' and workspace 'workspacepl33rpdmp2wolmyn'. Cause: 'Signature key pair for workspace 'workspacepl33rpdmp2wolmyn' already exists'
	at org.eclipse.che.multiuser.machine.authentication.server.MachineTokenRegistry.createToken(MachineTokenRegistry.java:114)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineTokenRegistry.getOrCreateToken(MachineTokenRegistry.java:79)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineTokenProviderImpl.getToken(MachineTokenProviderImpl.java:77)
	at org.eclipse.che.api.workspace.server.spi.provision.env.MachineTokenEnvVarProvider.get(MachineTokenEnvVarProvider.java:42)
	at org.eclipse.che.api.workspace.server.spi.provision.env.EnvVarEnvironmentProvisioner.provision(EnvVarEnvironmentProvisioner.java:46)
	at org.eclipse.che.api.workspace.server.spi.RuntimeInfrastructure.prepare(RuntimeInfrastructure.java:102)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startAsync(WorkspaceRuntimes.java:369)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$$EnhancerByGuice$$d62509db.CGLIB$startAsync$16(<generated>)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$$EnhancerByGuice$$d62509db$$FastClassByGuice$$9838240d.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at com.redhat.che.plugin.analytics.wsmaster.StartNumberSetterInterceptor.invoke(StartNumberSetterInterceptor.java:52)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$$EnhancerByGuice$$d62509db.startAsync(<generated>)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startAsync(WorkspaceManager.java:377)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startWorkspace(WorkspaceManager.java:307)
	at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager.startWorkspace(LimitsCheckingWorkspaceManager.java:121)
	at org.eclipse.che.api.workspace.server.WorkspaceService.startById(WorkspaceService.java:349)
	at sun.reflect.GeneratedMethodAccessor598.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:53)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:151)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter$$EnhancerByGuice$$4b0b4345.CGLIB$doFilter$0(<generated>)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter$$EnhancerByGuice$$4b0b4345$$FastClassByGuice$$1ab14e0c.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:51)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter$$EnhancerByGuice$$4b0b4345.doFilter(<generated>)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:70)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$$EnhancerByGuice$$be3b30b.CGLIB$doFilter$0(<generated>)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$$EnhancerByGuice$$be3b30b$$FastClassByGuice$$d62dde69.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:51)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$$EnhancerByGuice$$be3b30b.doFilter(<generated>)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:114)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:58)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManagerException: Signature key pair for workspace 'workspacepl33rpdmp2wolmyn' already exists
	at org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager.getOrCreateKeyPair(SignatureKeyManager.java:107)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineTokenRegistry.createToken(MachineTokenRegistry.java:91)
	... 88 common frames omitted
Caused by: org.eclipse.che.api.core.ConflictException: Signature key pair for workspace 'workspacepl33rpdmp2wolmyn' already exists
	at org.eclipse.che.multiuser.machine.authentication.server.signature.jpa.JpaSignatureKeyDao.create(JpaSignatureKeyDao.java:65)
	at org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager.generateKeyPair(SignatureKeyManager.java:139)
	at org.eclipse.che.multiuser.machine.authentication.server.signature.SignatureKeyManager.getOrCreateKeyPair(SignatureKeyManager.java:102)
	... 89 common frames omitted
```

**Comment by ibuziuk** [comment]
> Today, another account became broken. The account is for user osiotest1a on 1a cluster

cleanup is done. Some details:
- `workspace4cjpqr46i0h5xadk.dockerimage` deployment has been run for 5 days
- che 6 workspace `eclipse/ubuntu_jdk8` image @Katka92 are we testing che 6 periodically against the ubuntu stack / image? if this is the case it need to be changed to `centos` one
- routes, services has been also cleaned

**Comment by Katka92** [comment]
@ibuziuk The image we are using is ``` che/vertx ``` for our specific project. But we use upstream DialogAbout test, which tests really basics (workspace was started, IDE was loaded) and this is the only one using upstream image (the ubuntu one). 
If you think that it can be problem using this image, we can simply remove this test from our suite. I don't think it is worth rewriting as this test doesn't have that much value.

**Comment by ibuziuk** [comment]
@Katka92 no need to update anything related to Che 6 test suite. Let's leave it as is. please sync with @rhopp regarding Che 7 test strategy for che.openshift.io to be on the same page. Ideally, we should have the possibility to reuse and run any upstream che 7 test in the downstream.

**Comment by ibuziuk** [comment]
Since kibana is back I started to investigate the issue again and the data regarding untracked deployments is different now. Zabbix provides the following data atm regarding potential problematic workspaces:

- 1a - no suspicious workspace deployments detected
- 1b - no suspicious workspace deployments detected
- 2 - no suspicious workspace deployments detected
- 2a - 3 suspicious workspace deployments detected (04.20 there was a sufficient drop from 10 to 3):

![image](https://user-images.githubusercontent.com/1461122/56888810-3b4b0180-6a75-11e9-9abb-087c49e9734d.png)

Basically, atm there are only 3 suspicious deployments on 2a (on other OSIO cluster all workspaces have been idled at some point of time during the last 6 hours)

**Comment by ibuziuk** [comment]
take a look at workspace pods on `2a`:

> 0/1       Evicted                 0          44d
> 0/1       Evicted                 0          12d
> 1/1       Running                 0          11d
> 0/1       Evicted                 0          44d
> 0/1       Evicted                 0          44d
> 1/1       Running                 0          11d
> 0/1       Terminating             0          2h
> 1/1       Running                 0          11m
> 0/1       Completed               0          19d
> 1/1       Running                 3          44d

- found no traces about underlying workspaces in kibana
- quite a few of those pods have `Evicted` status @pbergene @jfchevrette any ideas how workspace pod could end up being in this state for 44 days?

**Comment by ScrewTSW** [comment]
I've encountered the same issue with our `osiotest-workspace-2a` account running on `starter-us-east-2a` on `production` environment.

**Comment by rhopp** [comment]
I took a look into kibana for logs of that workspace (https://logs.dsaas.openshift.com/goto/46a39e0f655490ee9fcf42f40a57bc1e). 

From logs it seems, that the workspace never got to "Stopped" state. After log entry "workspace is stopping" follows directly "workspace remove". Usually there is also "workspace is stopped" between them as seen for example on this search: https://logs.dsaas.openshift.com/goto/df07cb54c7166240cc9c6dcf700af990

**Comment by ibuziuk** [comment]
I take a look at zabbix and there are no untracked deployments across 4 clusters anymore. Closing
