### ISSUE TITLE
Auth deprovisioning failures (during Che User deletion)

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1450]
"workspace" is currently running and cannot be removed during `DELETE /api/user` calls - https://github.com/redhat-developer/rh-che/issues/1297

> {
> "message": "The workspace 'workspace_id' is currently running and cannot be removed."
> }
> 

https://docs.google.com/spreadsheets/d/1y37mCwsxwonnTmrYOiG0SdH_6Hz7XDtQqHHJMnMpzPg/edit#gid=0

**Comment by ibuziuk** [comment]
cc: @alexeykazakov @xcoulon

**Comment by skabashnyuk** [comment]
workspaces are not removed because of this 
```
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Error occurred during runtime 'workspace3x33jrpiwv6a7z0t:8eb306a7-336f-4810-a15c-65104f2165db' consistency checking. Cause: Exception during the user tenant data retrieval or parsing
at org.eclipse.che.workspace.infrastructure.kubernetes.InconsistentRuntimesDetector.checkOne(InconsistentRuntimesDetector.java:85)
at org.eclipse.che.workspace.infrastructure.kubernetes.InconsistentRuntimesDetector.check(InconsistentRuntimesDetector.java:63)
at sun.reflect.GeneratedMethodAccessor1269.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:63)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)\nCaused by: org.eclipse.che.api.workspace.server.spi.InfrastructureException: Exception during the user tenant data retrieval or parsing
at com.redhat.che.multitenant.tenantdata.TenantDataProvider.getUserCheTenantData(TenantDataProvider.java:75)
at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.getUserCheTenantData(Fabric8WorkspaceEnvironmentProvider.java:172)
at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.getWorkspacesOpenshiftConfig(Fabric8WorkspaceEnvironmentProvider.java:111)
at com.redhat.che.multitenant.Fabric8OpenShiftClientFactory.buildConfig(Fabric8OpenShiftClientFactory.java:126)
at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:87)
at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.findPod(KubernetesDeployments.java:898)
at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.get(KubernetesDeployments.java:257)
at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.isConsistent(KubernetesInternalRuntime.java:939)
at org.eclipse.che.workspace.infrastructure.kubernetes.InconsistentRuntimesDetector.checkOne(InconsistentRuntimesDetector.java:80)
... 12 common frames omitted\nCaused by: org.eclipse.che.api.workspace.server.spi.InfrastructureException: Exception during the user tenant data retrieval
at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.load(TenantDataCacheLoader.java:54)
at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.load(TenantDataCacheLoader.java:35)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
at com.redhat.che.multitenant.tenantdata.TenantDataProvider.getUserCheTenantData(TenantDataProvider.java:72)
... 20 common frames omitted\nCaused by: java.io.IOException: Failed access: https://api.openshift.io/api/user/services?token, method: GET, response code: 500, message: {\"errors\":[{\"code\":\"internal_error\",\"detail\":\"Unknown response: '500 Internal Server Error' (500)\",\"status\":\"500\",\"title\":\"Internal error\"}]}\n
at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:285)
at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.getResponseBody(TenantDataCacheLoader.java:91)
at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.load(TenantDataCacheLoader.java:52)
... 29 common frames omitted\n
```

**Comment by ibuziuk** [comment]
> ... 20 common frames omitted\nCaused by: java.io.IOException: Failed access: https://api.openshift.io/api/user/services?token, method: GET, response code: 500, message: {\"errors\":[{\"code\":\"internal_error\",\"detail\":\"Unknown response: '500 Internal Server Error' (500)\",\"status\":\"500\",\"title\":\"Internal error\"}]}\n

@alexeykazakov @sbryzak ^

**Comment by ibuziuk** [comment]
Closing as outdated
