### ISSUE TITLE
Could not update workspace after creation to add the 'sourceTypes' attribute 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1613]
> java.lang.NullPointerException: null
> 	at com.redhat.che.plugin.analytics.wsmaster.AttributesCompleter$1.onEvent(AttributesCompleter.java:51)
> 	at com.redhat.che.plugin.analytics.wsmaster.AttributesCompleter$1.onEvent(AttributesCompleter.java:44)
> 	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:108)
> 	at org.eclipse.che.api.workspace.server.WorkspaceManager.doCreateWorkspace(WorkspaceManager.java:566)
> 	at org.eclipse.che.api.workspace.server.WorkspaceManager.doCreateWorkspace(WorkspaceManager.java:537)
> 	at org.eclipse.che.api.workspace.server.WorkspaceManager.createWorkspace(WorkspaceManager.java:171)
> 	at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager$$EnhancerByGuice$$37cb0b38.CGLIB$createWorkspace$12(<generated>)
> 	at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager$$EnhancerByGuice$$37cb0b38$$FastClassByGuice$$931a59ae.invoke(<generated>)
> 	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
> 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
> 	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:60)
> 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
> 	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
> 	at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager$$EnhancerByGuice$$37cb0b38.createWorkspace(<generated>)
> 	at org.eclipse.che.api.workspace.server.WorkspaceService.create(WorkspaceService.java:266)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
> 	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
> 	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
> 	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
> 	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
> 	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
> 	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
> 	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
> 	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
> 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
> 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
> 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
> 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
> 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
> 	at org.eclipse.che.core.metrics.ApiResponseMe
>

**Comment by ibuziuk** [comment]
should be closed after 7.2.0 rollout to production

**Comment by ibuziuk** [comment]
fixed after 7.3.1 rollout to prod. Closing
