### ISSUE TITLE
Unclear exception during workspace stop with machine token

### ISSUE THREAD

**Issue by skabashnyuk** [redhat-developer/rh-che#1689]
**Issue problem:** 
When I've tried to analyze https://github.com/eclipse/che/issues/15006 on che.openshift.io
I noticed such errors in che-server logs
```
Error occurred during stopping of runtime 'workspaceydxoso4x49w73ggu:default:0a40b348-5982-41fb-a8da-e0176cdc2e3c' by user 'vgulyy'. Error: Error(s) occurs while cleaning up the namespace. Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing
````
```
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Error(s) occurs while cleaning up the namespace. Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing Exception during the user tenant data retrieval or parsing
    at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:192)
    at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:104)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:562)
    at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:60)
    at org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:177)
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:893)
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
    at io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
The final reason is unknown. I think it's some how related to the way how exceptions are propaged here https://github.com/redhat-developer/rh-che/blob/f06f903c028c33e3e2961787803c4a9f36a9c478/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/tenantdata/TenantDataCacheLoader.java#L49-L81

https://github.com/redhat-developer/rh-che/blob/63689ae430d087b5706df883e0d46c0117aabd51/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/tenantdata/TenantDataProvider.java#L74-L75

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Same as https://github.com/eclipse/che/issues/15006

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [X] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
Fixed in https://github.com/redhat-developer/rh-che/pull/1694 
Closing
