### ISSUE TITLE
After 7.7.1 update PVC based workspace are failed for users with usernames != <namepsace> name

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1771]
**Issue problem:** 
After 7.7.1 update PVC based workspace are failed for users with usernames != <namepsace> name. Ephemeral (emptyDir volume namespace work just fine)

version: (help/about menu)

 - [ ] Hosted Che 7.7.1 / 7.7.1b

**Reproduction Steps:**

- Have an account where username = email
- Start default ephemeral emptyDir workspace
- SUCCESS: workspace startup works just fine
- Stop the workspace and turn off the ephemeral toggle
- ERROR: workspace is failed to start with the following message:

> Error: Failed to run the workspace: "Failure executing: GET at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/ibuziuk@redhat.com-che/pods/mkdir-workspacexjhg28wbmpxn4pdj. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked.."

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

```
logs:

org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Failure executing: GET at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/blue.granite-che/pods/mkdir-workspace1pjk8i5p0pcz8brk. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked..
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:815)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:274)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:873)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:30)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/blue.granite-che/pods/mkdir-workspace1pjk8i5p0pcz8brk. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:413)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:794)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:210)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.delete(KubernetesDeployments.java:738)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.PVCSubPathHelper.execute(PVCSubPathHelper.java:185)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.PVCSubPathHelper.createDirs(PVCSubPathHelper.java:120)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.CommonPVCStrategy.prepare(CommonPVCStrategy.java:218)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.PrepareStorage.execute(PrepareStorage.java:63)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.ListenBrokerEvents.execute(ListenBrokerEvents.java:63)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:124)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:80)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:182)
	... 11 common frames omitted
```

**Comment by ibuziuk** [comment]
PR sent - https://github.com/redhat-developer/rh-che/pull/1772

**Comment by ibuziuk** [comment]
PR for prod update - https://github.com/openshiftio/saas-openshiftio/pull/1376

**Comment by ibuziuk** [comment]
fix has been applied to prod.Closing
