### ISSUE TITLE
Token is invalid

### ISSUE THREAD

**Issue by skabashnyuk** [redhat-developer/rh-che#1789]
**Issue problem:** 
Error in the logs

```
{"@timestamp":"2020-01-22T11:11:26.740+00:00","@version":1,"message":"Failed access: https://auth.openshift.io/api/user/services?token , method: GET, response code: 401, message: {"errors":[{"code":"token_validation_failed","detail":"token is invalid","id":"7j4QvtG+","status":"401","title":"Unauthorized"}]}
","logger_name":"com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader","thread_name":"http-nio-8080-exec-3","level":"ERROR","level_value":40000,"stack_trace":"java.io.IOException: Failed access: https://auth.openshift.io/api/user/services?token , method: GET, response code: 401, message: {"errors":[{"code":"token_validation_failed","detail":"token is invalid","id":"7j4QvtG+","status":"401","title":"Unauthorized"}]}

	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:285)
	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
	at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.getResponseBody(TenantDataCacheLoader.java:104)
	at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.load(TenantDataCacheLoader.java:57)
	at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.load(TenantDataCacheLoader.java:38)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.redhat.che.multitenant.tenantdata.TenantDataProvider.getUserCheTenantData(TenantDataProvider.java:72)
	at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.getUserCheTenantData(Fabric8WorkspaceEnvironmentProvider.java:172)
	at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.getWorkspacesOpenshiftConfig(Fabric8WorkspaceEnvironmentProvider.java:111)
	at com.redhat.che.multitenant.Fabric8OpenShiftClientFactory.buildConfig(Fabric8OpenShiftClientFactory.java:129)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:103)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesRecipeParser.parse(KubernetesRecipeParser.java:97)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesRecipeParser.parse(KubernetesRecipeParser.java:72)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentFactory.doCreate(KubernetesEnvironmentFactory.java:93)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentFactory.doCreate(KubernetesEnvironmentFactory.java:58)
	at org.eclipse.che.api.workspace.server.spi.environment.InternalEnvironmentFactory.create(InternalEnvironmentFactory.java:108)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.createInternalEnvironment(WorkspaceRuntimes.java:750)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.recoverOne(WorkspaceRuntimes.java:707)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.getInternalRuntime(WorkspaceRuntimes.java:358)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.injectRuntime(WorkspaceRuntimes.java:306)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.normalizeState(WorkspaceManager.java:520)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.getWorkspace(WorkspaceManager.java:207)
	at org.eclipse.che.api.workspace.activity.WorkspaceActivityService.active(WorkspaceActivityService.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.core.metrics.ApiResponseMetricFilter.doFilter(ApiResponseMetricFilter.java:46)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:49)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter.doFilter(KeycloakEnvironmentInitializationFilter.java:90)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter$$EnhancerByGuice$$d156e3b8.CGLIB$doFilter$0(<generated>)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter$$EnhancerByGuice$$d156e3b8$$FastClassByGuice$$1356dc31.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:52)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter$$EnhancerByGuice$$d156e3b8.doFilter(<generated>)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:125)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:74)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter$$EnhancerByGuice$$f2b8f36c.CGLIB$doFilter$0(<generated>)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter$$EnhancerByGuice$$f2b8f36c$$FastClassByGuice$$dad4d27f.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:52)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter$$EnhancerByGuice$$f2b8f36c.doFilter(<generated>)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
","identity_id":"0a40b348-XXXX"}

**Comment by ibuziuk** [comment]
Closing as outdated
