### ISSUE TITLE
ConcurrentModificationException in WorkspaceSubjectsRegistry

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1818]
**Issue problem:** 
WorkspaceSubjectsRegistry is not thread-safe

> java.util.ConcurrentModificationException: null
> 	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1651)
> 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
> 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
> 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:536)
> 	at com.redhat.che.multitenant.WorkspaceSubjectsRegistry.getSubject(WorkspaceSubjectsRegistry.java:96)
> 	at com.redhat.che.multitenant.Fabric8OpenShiftClientFactory.buildConfig(Fabric8OpenShiftClientFactory.java:96)
> 	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:89)
> 	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.findPod(KubernetesDeployments.java:938)
> 	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.getPodName(KubernetesDeployments.java:976)
> 	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.doDeleteDeployment(KubernetesDeployments.java:823)
> 	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.delete(KubernetesDeployments.java:780)
> 	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:256)
> 	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:155)
> 	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:573)
> 	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
> 	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:177)
> 	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:946)
> 	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
> 	at io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:30)
> 	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:74)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by ibuziuk** [comment]
PR sent https://github.com/redhat-developer/rh-che/pull/1879
