### ISSUE TITLE
Cannot start Json LS agent on rh-che stacks

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#188]
Currently when trying to unable the json ls server, it fails at startup:

    
![eclipse che test-wksp-jwhq - google chrome_039](https://user-images.githubusercontent.com/650571/28112540-a851a0f8-66f9-11e7-8371-c304ab35643a.png)

To reproduce locally with rh-che / minishift:

- in Che dashboard `stacks` section, duplicate the `Java CentOS` stack
- edit the created stack and activate `JSON language server` in the `Runtimes` > `DEV-MACHINE` > `Stacks` section
- create a workspace using that stack

**Comment by l0rd** [comment]
Thanks @sunix for reporting this. Any error in agent or che-server logs?

**Comment by sunix** [comment]
@l0rd no unfortunately :(

**Comment by l0rd** [comment]
May be related to #189

**Comment by l0rd** [comment]
@JPinkney do you know if that's solved?

**Comment by JPinkney** [comment]
This is still occurring. I'll assign it to myself and make it part of the stack fixes.

**Comment by l0rd** [comment]
@JPinkney any news on this one?

**Comment by JPinkney** [comment]
Still failing, it looks like node isn't installing

```bash
## Inspecting system...
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m
 
 
 
## Installing the NodeSource Node.js 6.x repo...
 
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
 
## Confirming "el7-x86_64" is supported...
 
+ mktemp
 
## Downloading release setup RPM...
 
+ curl -sL -o '/tmp/tmp.8kmZk1GJ5y' 'https://rpm.nodesource.com/pub_6.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
+ rpm -i --nosignature --force '/tmp/tmp.8kmZk1GJ5y'
 
Error executing command, exiting
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
## Installing release setup RPM...
 
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, ovl
[Errno 13] Permission denied: '/var/lib/rpm/Sha1header'
ovl: Error while doing RPMdb copy-up:
You need to be root to perform this command.
2018/02/02 00:50:08 Start new terminal.
2018-02-02 00:50:15,208[ost-startStop-1]  [INFO ] [i.WorkspaceProjectSynchronizer 63]   - API Endpoint: http://che-mini-che.192.168.64.37.nip.io/api
2018-02-02 00:50:15,199[ost-startStop-1]  [INFO ] [i.WorkspaceProjectSynchronizer 62]   - Workspace ID: workspacewvd1th8fb8wyqaoc
Fri Feb 02 00:50:16 UTC 2018 - [localhost-startStop-1] Product-specified preferences called before plugin is started
2018-02-02 00:50:17,593[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-4401"]
2018-02-02 00:50:17,584[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/che/ws-agent/webapps/ROOT.war] has finished in [12,625] ms
2018-02-02 00:50:17,617[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 13005 ms
2018-02-02 00:51:25,845[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:129)
	at com.sun.proxy.$Proxy87.initialize(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:77)
	at org.eclipse.che.api.languageserver.service.LanguageServerInitializationHandler.lambda$new$0(LanguageServerInitializationHandler.java:37)
	at org.eclipse.che.api.languageserver.registry.ServerInitializerImpl.initialize(ServerInitializerImpl.java:117)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
	at org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl.initialize(LanguageServerRegistryImpl.java:136)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToOne.lambda$withFunction$0(FunctionConfiguratorOneToOne.java:75)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
Caused by: java.io.IOException: Stream closed
java.lang.RuntimeException: java.io.IOException: Stream closed
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.OutputStream.write(OutputStream.java:116)
	... 16 common frames omitted
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:65)
```

**Comment by ibuziuk** [comment]
seems to work just fine
![image](https://user-images.githubusercontent.com/1461122/56970925-7b3ee100-6b68-11e9-9fbf-e2dc5261201a.png)

@sunix closing. Feel free to re-open if you are still facing this issue
