### ISSUE TITLE
Stopping workspace does not delete deployment on openshift

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#325]
Using Che on OSIO (2.0.5), when stopping workspace (does not matter if I do it via UI or via rest API), the deployment on openshift is not deleted, and as a result next try of starting that workspace fails. (starting it once again works, because the failed start deletes the deployment).
There is an exception in log when stopping workspace:
```
2017-09-07 07:58:08,958[aceSharedPool-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 700]    - Workspace 'che/k7b5bm47' with id 'workspaceb7ncvmtqb4as2eta' is being stopped by user 'che'
--
  | 2017-09-07 07:58:09,283[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route exec-agent-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:09,349[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route server-4403-tcp-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:09,361[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route terminal-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:09,374[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route vertx-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:09,391[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route wsagent-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:09,402[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 62]   - Removing OpenShift Service che-ws-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:09,442[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 67]   - Removing OpenShift Deployment che-ws-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:09,487[aceSharedPool-4]  [ERROR] [e.c.a.e.s.CheEnvironmentEngine 1145] - Could not destroy machine 'machinefapesvhacmkypaet' of workspace 'workspaceb7ncvmtqb4as2eta'
  | java.lang.NullPointerException: null
  | at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl$DeploymentReaper.reap(DeploymentOperationsImpl.java:178)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:555)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:68)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:596)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:584)
  | at io.fabric8.kubernetes.client.handlers.DeploymentHandler.delete(DeploymentHandler.java:63)
  | at io.fabric8.kubernetes.client.handlers.DeploymentHandler.delete(DeploymentHandler.java:32)
  | at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.delete(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:160)
  | at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.delete(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:59)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftDeploymentCleaner.cleanUpWorkspaceResources(OpenShiftDeploymentCleaner.java:68)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftDeploymentCleaner.cleanDeploymentResources(OpenShiftDeploymentCleaner.java:36)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.removeContainer(OpenShiftConnector.java:642)
  | at org.eclipse.che.plugin.docker.machine.DockerInstance.destroy(DockerInstance.java:282)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyMachine(CheEnvironmentEngine.java:1168)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.destroyEnvironment(CheEnvironmentEngine.java:1143)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.stop(CheEnvironmentEngine.java:321)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stopEnvironmentAndPublishEvents(WorkspaceRuntimes.java:788)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.stop(WorkspaceRuntimes.java:356)
  | at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$stopAsync$3(WorkspaceManager.java:732)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28)
  | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | 2017-09-07 07:58:09,489[aceSharedPool-4]  [INFO ] [e.c.a.w.s.i.ServerIdleDetector 80]   - Idling che server scheduled [timeout=3600] seconds]
  | 2017-09-07 07:58:09,489[aceSharedPool-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 733]    - Workspace 'che/k7b5bm47' with id 'workspaceb7ncvmtqb4as2eta' stopped by user 'che'
```

And the next start of workspace fails on with this log (deployment already exists):
```
2017-09-07 07:58:40,036[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 840]  - Created ImageStream rhche_vertx.
--
  | 2017-09-07 07:58:42,242[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1437] - Created ImageStreamTag rhche_vertx:che-ws-b7ncvmtqb4as2etacogly3yqk0tt7r1w in namespace rhopp-che
  | 2017-09-07 07:58:42,367[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1243] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
  | 2017-09-07 07:58:42,684[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1243] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
  | 2017-09-07 07:58:42,686[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 475]  - Che property 'che.openshift.workspace.memory.override' used to override workspace memory limit to 2300Mi.
  | 2017-09-07 07:58:42,779[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1298] - OpenShift service che-ws-b7ncvmtqb4as2eta created
  | 2017-09-07 07:58:42,839[aceSharedPool-5]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 77]   - OpenShift route wsagent-b7ncvmtqb4as2eta created
  | 2017-09-07 07:58:42,902[aceSharedPool-5]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 77]   - OpenShift route exec-agent-b7ncvmtqb4as2eta created
  | 2017-09-07 07:58:42,965[aceSharedPool-5]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 77]   - OpenShift route server-4403-tcp-b7ncvmtqb4as2eta created
  | 2017-09-07 07:58:43,026[aceSharedPool-5]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 77]   - OpenShift route terminal-b7ncvmtqb4as2eta created
  | 2017-09-07 07:58:43,086[aceSharedPool-5]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 77]   - OpenShift route vertx-b7ncvmtqb4as2eta created
  | 2017-09-07 07:58:43,087[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1330] - Creating OpenShift deployment che-ws-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,087[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1335] - Adding container b7ncvmtqb4as2eta-machinecogly3yqk0tt7r1w-che-dev-machine to OpenShift deployment che-ws-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,087[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 35]   - Container environment variables:
  | 2017-09-07 07:58:43,087[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - MAVEN_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1300m -Xms256m
  | 2017-09-07 07:58:43,087[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_LOCAL_CONF_DIR=/mnt/che/conf
  | 2017-09-07 07:58:43,088[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - USER_TOKEN=dummy_token
  | 2017-09-07 07:58:43,088[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_MACHINE_NAME=dev-machine
  | 2017-09-07 07:58:43,088[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1300m -Xms256m
  | 2017-09-07 07:58:43,088[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_WORKSPACE_ID=workspaceb7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,088[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_PROJECTS_ROOT=/projects
  | 2017-09-07 07:58:43,088[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_IS_DEV_MACHINE=true
  | 2017-09-07 07:58:43,089[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_API=http://che-host:8080/wsmaster/api
  | 2017-09-07 07:58:43,266[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 538]  - Error while creating Pod, removing deployment
  | 2017-09-07 07:58:43,267[aceSharedPool-5]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 539]  - Failure executing: POST at: https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/rhopp-che/deployments. Message: deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=extensions, kind=deployments, name=che-ws-b7ncvmtqb4as2eta, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
  | 2017-09-07 07:58:43,550[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route exec-agent-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,625[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route server-4403-tcp-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,640[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route terminal-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,660[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route vertx-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,690[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 56]   - Removing OpenShift Route wsagent-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,701[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 62]   - Removing OpenShift Service che-ws-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,729[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 67]   - Removing OpenShift Deployment che-ws-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:43,898[aceSharedPool-5]  [INFO ] [o.c.OpenShiftDeploymentCleaner 72]   - Removing OpenShift ReplicaSets for deployment che-ws-b7ncvmtqb4as2eta
  | 2017-09-07 07:58:44,084[aceSharedPool-5]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Failure executing: POST at: https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/rhopp-che/deployments. Message: deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=extensions, kind=deployments, name=che-ws-b7ncvmtqb4as2eta, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
  | org.eclipse.che.api.core.ServerException: Failure executing: POST at: https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/rhopp-che/deployments. Message: deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=extensions, kind=deployments, name=che-ws-b7ncvmtqb4as2eta, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1001)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:794)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:262)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.eclipse.che.api.core.ServerException: Failure executing: POST at: https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/rhopp-che/deployments. Message: deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=extensions, kind=deployments, name=che-ws-b7ncvmtqb4as2eta, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:396)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:765)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:938)
  | ... 11 common frames omitted
  | Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/rhopp-che/deployments. Message: deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=extensions, kind=deployments, name=che-ws-b7ncvmtqb4as2eta, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=deployments.extensions "che-ws-b7ncvmtqb4as2eta" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:320)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:269)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:239)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:210)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:699)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:324)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createOpenShiftDeployment(OpenShiftConnector.java:1393)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createContainer(OpenShiftConnector.java:519)
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:643)
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:352)
  | ... 13 common frames omitted


```

**Comment by ibuziuk** [comment]
Upstream issue - https://bugzilla.redhat.com/show_bug.cgi?id=1482337

**Comment by ibuziuk** [comment]
There is also upstream issue in openshift.io - https://github.com/openshiftio/openshift.io/issues/652

**Comment by l0rd** [comment]
The upstream fix for this has been merged https://bugzilla.redhat.com/show_bug.cgi?id=1481801#c21 We need to figure out when the fix will be available on OSIO and if it really address our problem.

**Comment by l0rd** [comment]
@kbsingh do you know if [this](https://bugzilla.redhat.com/show_bug.cgi?id=1481801#c21) fix will be in OSIO soon?

**Comment by l0rd** [comment]
As a workaround, if the fix is not deployed on OSIO soon, we could try to avoid using ImageStreams at all. But that would mean re-writing half of the OpenShiftConnector and it doesn't seems like a good idea right now.

**Comment by kbsingh** [comment]
@l0rd yes, this should be on the osio cluster within a few days. please re-check early next week.

**Comment by ibuziuk** [comment]
Checked after cluster wide tenant upgrade. The issue is still there

**Comment by ibuziuk** [comment]
> Cluster Info:
>     OC Version:      v3.6.173.0.37
>     Docker Version:  1.12.6-55.gitc4618fb.el7
>     Kube Version:    v1.6.1+5115d708d7
>     Metrics Version: v3.6.173.0.37
>     Logging Version: v3.6.173.0.37

Tested. Should be fixed now on prod cluster after the latest update. @rhopp Could you please verify & close ?

**Comment by rhopp** [comment]
Verified in production. Closing.
