### ISSUE TITLE
Starting a multi-machine workspace causes "Multiple ImageStreamTags found" error

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#363]
**Issue problem:** 

Che version 5.18.0 introduced a regression when starting a workspace with multiple machines (e.g. Java-MySQL-CentOS). I've been able to reproduce it on minishift. 

The problem is that the image tags for both machines matches and is well described in this upstream issue: https://github.com/eclipse/che/issues/6500 

```bash
2017-09-29 15:37:35,133[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Multiple ImageStreamTags found for name che-ws-dciqev5o0pjh6cq96k1rmn9umijkjkbu
org.eclipse.che.api.core.ServerException: Multiple ImageStreamTags found for name che-ws-dciqev5o0pjh6cq96k1rmn9umijkjkbu
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1002)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:794)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:262)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ibuziuk** [comment]
Upstream - https://github.com/eclipse/che/issues/6500

**Comment by gorkem** [comment]
This is not limited to multi-containers. I also get the same result when I try to start a workspace that was created earlier. Also I have observed that the deployments for a workspace even after they are deleted is not cleaned on minishift.

```
2017-10-01 13:21:56,830[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Multiple ImageStreamTags found for name che-ws-4uxufugewqxoqmd37u02fkfj2fm443zf
  | org.eclipse.che.api.core.ServerException: Multiple ImageStreamTags found for name che-ws-4uxufugewqxoqmd37u02fkfj2fm443zf
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1002)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:794)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:262)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:745)
 ```

**Comment by l0rd** [comment]
@ibuziuk @gorkem what version of minishift are you running?

On my local minishift when a Che workspace is cleaned up the imagestream is deleted too. And it looks like it's consistent with what I see on `openshift.io`. My local minishift version is:
```
$ minishift version
minishift v1.6.0+7a71565
```

**Comment by gorkem** [comment]
I am on minishift v1.5.0+ae62cf2

**Comment by ibuziuk** [comment]
@l0rd @gorkem  while testing stopping / deleting workspace on osio, `che-ws` image streams are deleted when workspace is stopped / deleted. So, for singe-machine stacks there should not be this `Multiple ImageStreamTags found` problem

**Comment by benoitf** [comment]
I got this error on `Multiple ImageStreamTags` with single machine only when I had incorrect docker images that were throwing "uncatched exceptions".

**Comment by ibuziuk** [comment]
could you define ` incorrect docker images` ?

**Comment by benoitf** [comment]
@ibuziuk like permission issue on the entrypoint

**Comment by ibuziuk** [comment]
hmm.. but this should not happen for predifined stacks, right ?

**Comment by benoitf** [comment]
@ibuziuk yes I never had this issue (cleanup not done) when using pre-defined images

**Comment by ibuziuk** [comment]
ok, thanks for clarifications. So, this issue should not be reproducible for osio for single machine workspaces

**Comment by ibuziuk** [comment]
PR with hot fix is sent - #6604

**Comment by ibuziuk** [comment]
PR is merged upstream and the fix should be available for rh-che after switching to 5.19.0 upstream release

**Comment by ibuziuk** [comment]
@rhopp could you please verify ?

**Comment by ibuziuk** [comment]
@rhopp closing. Feel free to reopen
