### ISSUE TITLE
[prod-preview] Problems with workspace deletion against multi-tenant che-server deployed on dedicated

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#430]
**Issue problem:** 
Workspace deletion is not working properly for mt che is deployed to prod-preview dedicated cluster https://console.rh-idev.openshift.com:

 - [X] I can reproduce it on latest official image

**Reproduction Steps:**
Create workspace from dashboard
Delete workspace from dashboard:

ERROR:

```
2017-11-14 13:40:08,569[entSubscriber-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
--
  | 2017-11-14 13:40:08,569[entSubscriber-4]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
  | 2017-11-14 13:40:08,595[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspacez1b01w36fc8djx8g' removed by user 'ibuziuk@redhat.com'
  | 2017-11-14 13:40:08,664[entSubscriber-4]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-4. Message: Failure executing: POST at: https://api.free-int.openshift.com/api/v1/namespaces/ibuziuk-che/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.free-int.openshift.com/api/v1/namespaces/ibuziuk-che/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:320)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:239)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:210)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:699)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:324)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftPvcHelper.createJobPod(OpenShiftPvcHelper.java:186)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.deleteWorkspacesOnPvc(OpenShiftWorkspaceFilesCleaner.java:120)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftWorkspaceFilesCleaner.clear(OpenShiftWorkspaceFilesCleaner.java:101)
  | at org.eclipse.che.plugin.docker.machine.cleaner.RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.lambda$onEvent$0(RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber.java:68)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)



```

**Comment by ibuziuk** [comment]
This issue is not reproducible with mt che server deployed on prod and workspace cleanup works just fine there:


```
2017-11-16 13:52:51,406[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 700]    - Workspace 'ibuziuk@redhat.com/wksp-yx52' with id 'workspacebdbym4yd2n35n974' is being stopped by user 'ibuziuk@redhat.com'
--
  | 2017-11-16 13:52:51,632[aceSharedPool-1]  [INFO ] [c8WorkspaceEnvironmentProvider 197]  - Retrieving user Che tenant data
  | 2017-11-16 13:52:51,695[aceSharedPool-1]  [INFO ] [c8WorkspaceEnvironmentProvider 230]  - cheTenantData = {ibuziuk-che,https://api.starter-us-east-2.openshift.com,null}
  | 2017-11-16 13:52:52,472[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route codeserver-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,738[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route exec-agent-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,759[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route server-22-tcp-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,783[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route server-4403-tcp-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,805[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route terminal-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,849[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route tomcat8-debug-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,873[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route vertx-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,897[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route vertx-debug-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,946[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route wsagent-bdbym4yd2n35n974
  | 2017-11-16 13:52:52,967[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 99]   - Removing OpenShift Service che-ws-bdbym4yd2n35n974
  | 2017-11-16 13:52:53,028[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 104]  - Removing OpenShift Deployment che-ws-bdbym4yd2n35n974
  | 2017-11-16 13:52:53,363[aceSharedPool-1]  [INFO ] [o.c.OpenShiftDeploymentCleaner 109]  - Removing OpenShift ReplicaSets for deployment che-ws-bdbym4yd2n35n974
  | 2017-11-16 13:52:53,618[aceSharedPool-1]  [INFO ] [c8WorkspaceEnvironmentProvider 197]  - Retrieving user Che tenant data
  | 2017-11-16 13:52:53,634[aceSharedPool-1]  [INFO ] [c8WorkspaceEnvironmentProvider 230]  - cheTenantData = {ibuziuk-che,https://api.starter-us-east-2.openshift.com,null}
  | 2017-11-16 13:52:54,071[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 733]    - Workspace 'ibuziuk@redhat.com/wksp-yx52' with id 'workspacebdbym4yd2n35n974' stopped by user 'ibuziuk@redhat.com'
  | 2017-11-16 13:52:54,935[entSubscriber-0]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 96]   - Synchronously deleting workspace workspacebdbym4yd2n35n974 on PVC claim-che-workspace
  | 2017-11-16 13:52:54,936[entSubscriber-0]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 118]  - Deleting 1 workspaces on PVC claim-che-workspace
  | 2017-11-16 13:52:54,940[entSubscriber-0]  [INFO ] [o.e.c.p.o.c.OpenShiftPvcHelper 146]  - Executing command rm in PVC claim-che-workspace for 2 dirs
  | 2017-11-16 13:52:54,962[nio-8080-exec-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 336]    - Workspace 'workspacebdbym4yd2n35n974' removed by user 'ibuziuk@redhat.com'

```

So, this might be some cluster regression problem (prod-preview is 3.7 / prod is 3.6)

**Comment by l0rd** [comment]
Not reproducible
