### ISSUE TITLE
Could not retrieve OSO token from Keycloak token

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#436]
Reproduced against multi-tenant che-server deployed on prod-preview dedicated

```

2017-11-15 17:30:27,067[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 807]    - Workspace 'mloriedo/wksp-plhv' with id 'workspacegjrb4ewfjinv9zeu' created by user 'mloriedo'
--
  | 2017-11-15 17:30:27,830[aceSharedPool-1]  [WARN ] [.e.c.p.d.m.MachineProviderImpl 569]  - Failed to check image che/vertx availability. Cause: Unable connect to unix socket: '/var/run/docker.sock'
  | 2017-11-15 17:30:27,878[aceSharedPool-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - java.lang.RuntimeException: Cound not retrieve OSO token from Keycloak token
  | org.eclipse.che.api.core.ServerException: java.lang.RuntimeException: Cound not retrieve OSO token from Keycloak token
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.eclipse.che.api.core.ServerException: java.lang.RuntimeException: Cound not retrieve OSO token from Keycloak token
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:401)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)
  | at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)
  | ... 11 common frames omitted
  | Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Cound not retrieve OSO token from Keycloak token
  | at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
  | at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
  | at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
  | at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
  | at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.getOpenShiftTokenForUser(Fabric8WorkspaceEnvironmentProvider.java:187)
  | at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.getWorkspacesOpenshiftConfig(Fabric8WorkspaceEnvironmentProvider.java:138)
  | at org.eclipse.che.plugin.openshift.client.OpenshiftWorkspaceEnvironmentProvider.getWorkspacesOpenshiftConfig(OpenshiftWorkspaceEnvironmentProvider.java:38)
  | at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.pull(OpenShiftConnector.java:994)
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.pullImage(MachineProviderImpl.java:539)
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:448)
  | at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:355)
  | ... 13 common frames omitted
  | Caused by: java.lang.RuntimeException: Cound not retrieve OSO token from Keycloak token
  | at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.loadOpenShiftTokenForUser(Fabric8WorkspaceEnvironmentProvider.java:168)
  | at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:146)
  | at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
  | at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
  | at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
  | at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
  | ... 23 common frames omitted
  | Caused by: java.io.IOException: Failed access: https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token?token, method: GET, response code: 400, message: {"errorMessage":"Invalid token."}
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:264)
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:152)
  | at org.eclipse.che.multiuser.keycloak.token.provider.service.KeycloakTokenProvider.getResponseBody(KeycloakTokenProvider.java:108)
  | at org.eclipse.che.multiuser.keycloak.token.provider.service.KeycloakTokenProvider.getAccessToken(KeycloakTokenProvider.java:93)
  | at org.eclipse.che.multiuser.keycloak.token.provider.service.KeycloakTokenProvider.obtainOsoToken(KeycloakTokenProvider.java:87)
  | at com.redhat.che.multitenant.Fabric8WorkspaceEnvironmentProvider.loadOpenShiftTokenForUser(Fabric8WorkspaceEnvironmentProvider.java:160)
  | ... 28 common frames omitted


```

**Comment by l0rd** [comment]
Not reproducible
