### ISSUE TITLE
[multi-tenant]  java.io.IOException: unexpected end of stream on Connection

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#437]
Reproduced against multi-tenant che-server deployed on prod-preview dedicated

```

2017-11-15 18:15:20,194[ted-scheduler-2]  [INFO ] [ockerAbandonedResourcesCleaner 126]  - List containers registered in the api: []
--
  | 2017-11-15 19:00:49,141[enshift.com/...]  [ERROR] [i.f.k.c.d.i.LogWatchCallback 80]     - Log Callback Failure.
  | java.io.IOException: unexpected end of stream on Connection{api.free-int.openshift.com:443, proxy=DIRECT hostAddress=api.free-int.openshift.com/34.196.64.84:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
  | at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
  | at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:89)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
  | at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
  | at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.io.EOFException: \n not found: size=0 content=…
  | at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
  | at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
  | ... 22 common frames omitted


```

**Comment by l0rd** [comment]
Not reproducible
