### ISSUE TITLE
Intermittent: Workspace pod fails to start due to volume mount failures

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#467]
**Issue problem:** 

Workspace pod sometimes fails to start.
Events of workspace pod:
![image pasted at 2017-12-5 14-11](https://user-images.githubusercontent.com/1215011/33610335-7c6da7da-d9cb-11e7-88cf-0f356ca92ce9.png)

Log from che-server:
```
2017-12-05 12:14:09,086[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1050] - Created ImageStream registry.devshift.net_che_vertx.
2017-12-05 12:14:11,379[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1825] - Created ImageStreamTag registry.devshift.net_che_vertx:235cwm44b8rlcz2fl0wmcks8uz7gbd in namespace rhopp-che
2017-12-05 12:14:11,380[aceSharedPool-4]  [WARN ] [o.e.c.p.o.c.OpenShiftConnector 569]  - Didn't find image 'eclipse-che/workspace235cwm44b8rlcz2f_machinel0wmcks8uz7gbdj1_rhoppredhatcom_dev-machine' in the map of created images
2017-12-05 12:14:11,638[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1616] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
2017-12-05 12:14:12,285[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1616] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
2017-12-05 12:14:12,286[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 655]  - Che property 'che.openshift.workspace.memory.override' used to override workspace memory limit to 2.4Gi.
2017-12-05 12:14:12,427[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1679] - OpenShift service che-ws-235cwm44b8rlcz2f created
2017-12-05 12:14:12,561[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route wsagent-235cwm44b8rlcz2f created
2017-12-05 12:14:12,692[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route exec-agent-235cwm44b8rlcz2f created
2017-12-05 12:14:12,823[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route server-4403-tcp-235cwm44b8rlcz2f created
2017-12-05 12:14:12,950[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route terminal-235cwm44b8rlcz2f created
2017-12-05 12:14:13,083[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route server-22-tcp-235cwm44b8rlcz2f created
2017-12-05 12:14:13,211[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route vertx-debug-235cwm44b8rlcz2f created
2017-12-05 12:14:13,346[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route tomcat8-debug-235cwm44b8rlcz2f created
2017-12-05 12:14:13,474[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route vertx-235cwm44b8rlcz2f created
2017-12-05 12:14:13,606[aceSharedPool-4]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route codeserver-235cwm44b8rlcz2f created
2017-12-05 12:14:13,607[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1713] - Creating OpenShift deployment che-ws-235cwm44b8rlcz2f
2017-12-05 12:14:13,607[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1718] - Adding container 235cwm44b8rlcz2f-machinel0wmcks8uz7gbdj1-rhoppredhatcom-dev-ma to OpenShift deployment che-ws-235cwm44b8rlcz2f
2017-12-05 12:14:13,607[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 35]   - Container environment variables:
2017-12-05 12:14:13,607[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - EXEC_AGENT_LOGS_DIR_SETTER=export EXEC_AGENT_LOGS_DIR="/workspace-logs/${CHE_MACHINE_NAME}-exec-agent"
2017-12-05 12:14:13,608[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - MAVEN_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m
2017-12-05 12:14:13,608[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_LOCAL_CONF_DIR=/mnt/che/conf
2017-12-05 12:14:13,608[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_LOGS_DIR_SETTER=export CHE_LOGS_DIR="/workspace-logs/${CHE_MACHINE_NAME}-ws-agent"
2017-12-05 12:14:13,608[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - USER_TOKEN=machinejmx6xrbcfa22geys95252i1qlnawfq14uzfouzkrfdxcbe5ynw8twlxibu4szqsogyuk4voqof51cixcwwbxesdku992kzukvb9dhdwzgjd3ztm79hk91jn2oyn7163m
2017-12-05 12:14:13,608[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_MACHINE_NAME=dev-machine
2017-12-05 12:14:13,608[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m
2017-12-05 12:14:13,609[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_WORKSPACE_ID=workspace235cwm44b8rlcz2f
2017-12-05 12:14:13,609[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_PROJECTS_ROOT=/projects
2017-12-05 12:14:13,609[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_IS_DEV_MACHINE=true
2017-12-05 12:14:13,609[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_API=https://che.openshift.io/wsmaster/api
2017-12-05 12:14:14,009[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1781] - OpenShift deployment che-ws-235cwm44b8rlcz2f created
2017-12-05 12:14:56,789[aceSharedPool-4]  [INFO ] [c8WorkspaceEnvironmentProvider 197]  - Retrieving user Che tenant data
2017-12-05 12:14:56,871[aceSharedPool-4]  [INFO ] [c8WorkspaceEnvironmentProvider 230]  - cheTenantData = {rhopp-che,https://api.starter-us-east-2.openshift.com,null}
2017-12-05 12:18:18,185[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 722]  - Error while creating Pod, removing deployment
2017-12-05 12:18:18,186[aceSharedPool-4]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 723]  - Failed to get the ID of the container running in the OpenShift pod
2017-12-05 12:18:18,826[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route codeserver-235cwm44b8rlcz2f
2017-12-05 12:18:18,957[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route exec-agent-235cwm44b8rlcz2f
2017-12-05 12:18:18,976[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route server-22-tcp-235cwm44b8rlcz2f
2017-12-05 12:18:18,995[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route server-4403-tcp-235cwm44b8rlcz2f
2017-12-05 12:18:19,015[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route terminal-235cwm44b8rlcz2f
2017-12-05 12:18:19,034[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route tomcat8-debug-235cwm44b8rlcz2f
2017-12-05 12:18:19,053[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route vertx-235cwm44b8rlcz2f
2017-12-05 12:18:19,074[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route vertx-debug-235cwm44b8rlcz2f
2017-12-05 12:18:19,093[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route wsagent-235cwm44b8rlcz2f
2017-12-05 12:18:19,112[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 99]   - Removing OpenShift Service che-ws-235cwm44b8rlcz2f
2017-12-05 12:18:19,152[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 104]  - Removing OpenShift Deployment che-ws-235cwm44b8rlcz2f
2017-12-05 12:18:19,371[aceSharedPool-4]  [INFO ] [o.c.OpenShiftDeploymentCleaner 109]  - Removing OpenShift ReplicaSets for deployment che-ws-235cwm44b8rlcz2f
2017-12-05 12:18:19,642[aceSharedPool-4]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Failed to get the ID of the container running in the OpenShift pod
org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ServerException: Failed to get the ID of the container running in the OpenShift pod
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:401)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)
        ... 11 common frames omitted
Caused by: org.eclipse.che.plugin.openshift.client.exception.OpenShiftException: Failed to get the ID of the container running in the OpenShift pod
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createContainer(OpenShiftConnector.java:714)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:648)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:357)
        ... 13 common frames omitted
Dec 05, 2017 12:21:39 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:21:42 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:21:42 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:21:46 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:21:49 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:21:49 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:21:54 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:21:57 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Dec 05, 2017 12:22:10 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

**Red Hat Che version:** 

Using che multitenant on prod (openshift.io). 5.21.0-SNAPSHOT

**Reproduction Steps:**

It sometimes happens when running tests, but I also reproduced it doing just curl calls to local che-starter.
Note, I had to edit `MultiTenantToggle#isMultiTenant` method to allways return true, as the account I'm using is multitenant this it would otherwise fail.

When che-starter is running, do:
1) `curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${ACTIVE_TOKEN}" -d $CREATE_WORKSPACE_JSON  "http://localhost:10000/workspace?masterUrl=https://console.starter-us-east-2.openshift.com&namespace=rhopp-che"`
2) wait for workspace to start.
3) do step 1) again until issue occurs (it took me 2-3 tries)

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Volume mount errors also happens when unidling che server but this does not cause any problems:


```
12:50:44 PM | che-1-61zhx | Pod | Warning | Failed mount | Unable to mount volumes for pod "che-1-61zhx_ibuziuk-che(698b724f-da7b-11e7-a6d5-02d7377a4b17)": timeout expired waiting for volumes to attach/mount for pod "ibuziuk-che"/"che-1-61zhx". list of unattached/unmounted volumes=[che-data-volume]
12:50:44 PM | che-1-61zhx | Pod | Warning | Failed sync | Error syncing pod
```

**Comment by ibuziuk** [comment]
First workspace is starting without any errors in the events. However, when starting second workspace when there is already one running there is a pvc error:


```
che-ws-kodkwsmbeecwc356-1847229639-c8n3v | Pod | Warning | Failed mount | Failed to attach volume "pvc-ae0f3f14-d8ea-11e7-8191-0233cba325d9" on node "ip-172-31-69-27.us-east-2.compute.internal" with: Error attaching EBS volume "vol-07e96497f791fc1e0" to instance "i-049d5220b249fa9bc": VolumeInUse: vol-07e96497f791fc1e0 is already attached to an instance status code: 400, request id: e9bec460-e92e-4ef0-b01c-457a8016c371. The volume is currently attached to instance "i-0061c08742c46477f"
-- | -- | -- | -- | --
```

**Comment by ibuziuk** [comment]
Testing results against multi-tenant che-server are the same:
first workspace is started without any problems, and there are a few pvc error during the startup of the second one:

```

1:18:03 PM | che-ws-4v72ij1ogu7d53dp-1451478756-8wsv6 | Pod | Warning | Failed mount | Unable to mount volumes for pod "che-ws-4v72ij1ogu7d53dp-1451478756-8wsv6_ibuziuk-osiotest1-che(3a67d59b-da7f-11e7-a6d5-02d7377a4b17)": timeout expired waiting for volumes to attach/mount for pod "ibuziuk-osiotest1-che"/"che-ws-4v72ij1ogu7d53dp-1451478756-8wsv6". list of unattached/unmounted volumes=[claim-che-workspace]
1:18:03 PM | che-ws-4v72ij1ogu7d53dp-1451478756-8wsv6 | Pod | Warning | Failed sync | Error syncing pod
```
But those pvc problems does not cause failures during the workspace startup - it just takes a bit (~15 secs) longer

**Comment by ibuziuk** [comment]
it usually takes ~20 secs for openshift to resolve the pvc issue, in your case it is not resolved after 4 minutes for some reason 
@rhopp could you please perform environment reset and try again ? (this problem is not multi-tenant specific IMO)

**Comment by rhopp** [comment]
I've just successfully reproduced this issue using Codebases UI. It took just 3 tries (created workspace, waited for it to start, created second workspace, waited for it to start, created third workspace -> this one failed to start with the same error)

**Comment by rhopp** [comment]
@ibuziuk fyi I've managed to try it ~5 times with my second multitenant account, but I wasn't able to reproduce the issue. Today I'm on PTO, but on friday I'm gonna give it few more shots to reproduce.

**Comment by rhopp** [comment]
I was able to reproduce it even with my second multitenant account.
I've written simple script to help with testing: https://gist.github.com/rhopp/d107bf55e495f8d935754d3457ebab90

**Comment by l0rd** [comment]
That looks like an OpenShift issue and looks like related to https://github.com/openshiftio/openshift.io/issues/666 we had in the past

**Comment by l0rd** [comment]
Not seen this one lately

**Comment by rhopp** [comment]
I'm reopening this one, as it is still sometimes seen on prod, as seen in this kibana search: https://logs.dsaas.openshift.com/goto/ce0f1dd614d4a674322616f30f5ae73a

**Comment by ibuziuk** [comment]
@rhopp Do we have a housekeeping issue for this ?

**Comment by ibuziuk** [comment]
Going to close this issue since it is already very well-tracked: 
 - https://github.com/openshiftio/openshift.io/issues/4079
 - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2169
