### ISSUE TITLE
Cannot create workspace on prod & prod-preview

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#530]
**Issue problem:** 
osio issue https://github.com/openshiftio/openshift.io/issues/2122
Either with manual creation or through che-starter, the workspace stays in state "STARTING", it loads and then fails to start.

https://pastebin.com/940ztbZq

**Red Hat Che version:** 

version:
* Version :1.0.0-SNAPSHOT
* Revision :bb8dee7ccecd2648
* Build Time :2018-01-29 14:43:56

 - [?] I can reproduce it on latest official image

**Reproduction Steps:**

Create any workspace, add project (unnecessary),wait. 

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
what are the openshift events ?

**Comment by ScrewTSW** [comment]
None to be noted.

Also, it seems to be working now. Maybe a one-time event?

**Comment by rhopp** [comment]
Today, this issue is also appearing on prod.
The workspace seems succesfully started (also the workspace pod on OSO is running):
![image](https://user-images.githubusercontent.com/1215011/35614661-236bc0b4-0670-11e8-888e-f358f8ee81ab.png)
But after while it times out with this error:
```
{"@timestamp":"2018-01-31T09:19:46.230+00:00","@version":1,"message":"Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"WorkspaceSharedPool-7","level":"ERROR","level_value":40000,"stack_trace":"org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
	at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:153)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:681)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:800)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"}
```

There are no suspicious events in OSO.

**Comment by rhopp** [comment]
When the failure/time occurs, there is this error in web browser console:
```
_app-0.js:372 Uncaught Error: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: 5 exceptions caught: (TypeError) : Cannot read property 'a' of null; (TypeError) : Cannot read property 'a' of null; (TypeError) : Cannot read property 'a' of null; (TypeError) : Cannot read property 'a' of null; (TypeError) : Cannot read property 'a' of null
    at EA.lo [as Jn] (VM977 _app-0.js:372)
    at EA.oo [as Ln] (VM977 _app-0.js:372)
    at EA.ko (VM977 _app-0.js:370)
    at EA.so (VM977 _app-0.js:374)
    at EA.wo (VM977 _app-0.js:378)
    at new EA (VM977 _app-0.js:812)
    at mA (VM977 _app-0.js:800)
    at Shk (VM977 _app-0.js:16804)
    at Uhk.Vhk [as Ir] (VM977 _app-0.js:16807)
    at qde (VM977 _app-0.js:3924)
    at Oce (VM977 _app-0.js:3904)
    at Ice (VM977 _app-0.js:3899)
    at gce (VM977 _app-0.js:3876)
    at UEi (VM977 _app-0.js:13322)
    at hce (VM977 _app-0.js:3877)
    at $ck (VM977 _app-0.js:16614)
    at ock.rck [as LG] (VM977 _app-0.js:16585)
    at WebSocket.onmessage (VM977 _app-0.js:16623)
lo @ _app-0.js:372
oo @ _app-0.js:372
ko @ _app-0.js:370
so @ _app-0.js:374
wo @ _app-0.js:378
EA @ _app-0.js:812
mA @ _app-0.js:800
Shk @ _app-0.js:16804
Vhk @ _app-0.js:16807
qde @ _app-0.js:3924
Oce @ _app-0.js:3904
Ice @ _app-0.js:3899
gce @ _app-0.js:3876
UEi @ _app-0.js:13322
hce @ _app-0.js:3877
$ck @ _app-0.js:16614
rck @ _app-0.js:16585
onmessage @ _app-0.js:16623
```

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW  does refresh helps ? this might be related to route flapping issue we had some time ago

**Comment by ScrewTSW** [comment]
@ibuziuk refreshing does nothing.

**Comment by ibuziuk** [comment]
@ScrewTSW thanks, I have figured out what causes the problem and commented in the upstream issue

**Comment by ibuziuk** [comment]
upstream issue is closed. Closing also this one. Fell free to reopen
