### ISSUE TITLE
On start of Che message `Admin admin not found yet.` appears

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#625]
https://errortracking.prod-preview.openshift.io/openshift_io/che6master/issues/2405/

```
Stacktrace (most recent call first):

    at org.eclipse.che.multiuser.api.permission.server.AdminPermissionInitializer.init(AdminPermissionInitializer.java:68)
    at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:46)

Admin admin not found yet.
```

**Comment by ibuziuk** [comment]
I think this one should be fixed. Assigning to me for verification

**Comment by ibuziuk** [comment]
Does not happen anymore, verified against 7.1.0. Closing
