### ISSUE TITLE
Git push sometimes fails

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#679]
**Issue problem:** 
I'm opening this issue mainly for discussion and ideas gathering (and also that it may as well be bug).
One of our functional tests case is simple: Have worskpace with project (and configured remote github repo) -> do some change -> commit -> push -> check whether the push was successfull.

The workspace is started using che-starter (so the github token should be injected correctly).

The problem is, that it SOMETIMES fails. I wasn't able to see any pattern. 

Here is video of it failing:
http://artifacts.ci.centos.org/devtools/che-functional-tests/devtools-che-functional-tests-prcheck-openshift.io/455/videos/redhat.che.functional.tests.GitTestCase/test_push_changes_failed.mp4

Unfortunately, I wasn't able to reproduce this running the tests on my local machine. So far, it only happened on ci.centos.org - We have currently two jobs, each running against different env with different user (One is against prod with user provisioned on 2a cluster, second is against prod-preview with user provisioned on free-stg cluster) and it intermittently happens on both jobs.

My most recent try of grasping this problem was to:
When the push fails, try to import github token programmatically from the tests again and try the push again. This failed (seen on video).
The code for injecting the github token is here: https://github.com/redhat-developer/che-functional-tests/pull/248/files#diff-b0c5a4784cee9177b74e04e1a814587cR145

I'm running out of ideas... Any idea/help appreciated.

**Comment by dmytro-ndp** [comment]
Make sure 
1. You have _GitHub Identity Provider_ with correct _Client ID_ and _Client Secret_
1. OAuth application settings on GitHub has correct _Homepage URL_ and _Authorization callback URL_
1. You are uploading SSH key on github.com from _Eclipse Che > Preferences_ window before test.

**Comment by rhopp** [comment]
In `/workspace_logs/ws-agent/archive/2018/05/23/catalinga.log` there was this exception:
```
2018-05-23 14:13:03,145[nio-4401-exec-1]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error
 occurred, error time: 2018-05-23 14:13:03                                                                     
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of push command           
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:198)                                         
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:85)                                          
        at org.eclipse.che.git.impl.jgit.JGitConnection.executeRemoteCommand(JGitConnection.java:2159)         
        at org.eclipse.che.git.impl.jgit.JGitConnection.push(JGitConnection.java:1480)                         
        at org.eclipse.che.api.git.GitService.push(GitService.java:405)                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                         
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                       
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)               
        at java.lang.reflect.Method.invoke(Method.java:498)                                                    
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)      
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)       
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)               
        at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)        
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)                       
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)                       
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)                 
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)                        
        at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)                          
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)                                        
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)               
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)                   
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)                     
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)            
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)             
        at org.eclipse.che.workspace.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:52)      
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)             
        at org.eclipse.che.multiuser.machine.authentication.agent.MachineLoginFilter.doFilter(MachineLoginFilter.java:84)                                                                                                     
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)             
        at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:294)                        
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:161)                                
        at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)                         
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)             
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)            
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)                                
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)   
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)           
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)                 
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)                  
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)                       
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)                        
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)                             
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)                    
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)                         
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)                          
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)                    
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)             
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)                 
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)                     
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                     
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                  
        at java.lang.Thread.run(Thread.java:748)                                                               
Caused by: java.io.IOException: Source ref log4j2 doesn't resolve to any object.                               
        at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:288)                         
        at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:192)                         
        at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:663)                    
        at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:1407)                   
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:166)                                         
        ... 51 common frames omitted      
```
Rings any bells @dmytro-ndp, @ibuziuk, @l0rd ?

**Comment by vinokurig** [comment]
According to Exception from `RemoteRefUpdate`I guess the problem was in connection to remote.

**Comment by dmytro-ndp** [comment]
Do you know which kind of problem it could be: authorization problem, or wrong address, or something else?

**Comment by vinokurig** [comment]
I think if it was authorization problem or wrong address, the error would say about that. May be the remote was unreachable.

**Comment by ibuziuk** [comment]
Closing as obsolete. Git push for Che 7 GA should be verified as part of the https://github.com/redhat-developer/rh-che/issues/1524
