### ISSUE TITLE
Current user ID ('0000-00-0000') is different from the user ID (''051b9a4c-3b52-451a-a977-621d25f424e3")

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#755]
https://errortracking.prod-preview.openshift.io/openshift_io/che6master/issues/4458/

```
Stacktrace (most recent call first):

    at com.redhat.che.multitenant.Fabric8OpenShiftClientFactory.buildConfig(Fabric8OpenShiftClientFactory.java:79)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:89)
    at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesPods.delete(KubernetesPods.java:527)
    at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:152)
    at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:85)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:455)
    at org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:179)
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:477)

Current user ID ('0000-00-0000') is different from the user ID ('051b9a4c-3b52-451a-a977-621d25f424e3') that started workspace workspaceo2tcro58m2i4apmf and subject of user that started workspace is not found in subjects cache
```

**Comment by ibuziuk** [comment]
Closing as out dated
