### ISSUE TITLE
Cannot set error status of the workspace workspace5d7pzbqefdotmcuw. Error is: The anonymous subje...

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#756]
https://errortracking.prod-preview.openshift.io/openshift_io/che6master/issues/3885/

```
Stacktrace (most recent call first):

    at org.eclipse.che.api.workspace.server.WorkspaceManager.handleStartupError(WorkspaceManager.java:423)
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$startAsync$2(WorkspaceManager.java:371)

Cannot set error status of the workspace workspace5d7pzbqefdotmcuw. Error is: The anonymous subject is used, and won't be able to perform this action
```

**Comment by ibuziuk** [comment]
Closing as outdated
