### ISSUE TITLE
Recurring WebSocket errors in the Che server log

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#926]
**Issue problem:** 

In the production and prod-preview Che server, we are now seeing regularly these warning messages in the logs:
- message: `Exec Failure`
- logger_name: `io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager`
- thread_name:
`OkHttp https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/...`
- stack_trace: 
```
java.io.EOFException: null
    at okio.RealBufferedSource.require(RealBufferedSource.java:60)
    at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
    at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)\n
```
**Red Hat Che version:** 

Current OSIO production and prod-preview environments

 - [ ] I can reproduce it on latest official image

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment]
Need to figure out if it's che 6 specific. If reproducible also on Che 7 we should make it P1

**Comment by ibuziuk** [comment]
Also reproducible in Che 7 (5 occurrences for the last 24 hours)

**Comment by ibuziuk** [comment]
Closing as outdated
